### ISSUE TITLE
is that any example for using it?

### ISSUE THREAD

**Issue by ChiaoTeo** [dfns/cggmp21#105]

**Comment by ChiaoTeo** [comment]
and I would like to ask, can this library be cross-compiled for Android?

**Comment by survived** [comment]
Library is extensively documented, you can find examples right in the docs, see https://docs.rs/cggmp21/. Hope that helps!

**Comment by survived** [comment]
> and I would like to ask, can this library be cross-compiled for Android?

We didn't check. If you can make GMP library work on Android, then you might be able to do the same for cggmp21 implementation. Implementation is almost pure-Rust except for GMP lib which is usually a blocker when you need to port it somewhere.

**Comment by ChiaoTeo** [comment]
I try ios\andriod, it works. thanks

**Comment by godenzim** [comment]
@ChiaoTeo Sorry to resurrect this closed issue, but I am also trying to cross compile to android but I am having issues with the GMP lib, can you share more details on how you managed to make it cross compile?

**Comment by ChiaoTeo** [comment]
> @ChiaoTeo抱歉，再次提起这个已解决的问题，但是我也试图交叉编译到 android，但是在 GMP lib 方面遇到了问题，您能否分享更多有关如何进行交叉编译的详细信息？

I modify gmplib build.rs, that's why it work
