### ISSUE TITLE
any plan for Ed25519?

### ISSUE THREAD

**Issue by ChiaoTeo** [dfns/cggmp21#108]

**Comment by survived** [comment]
We do have a separate protocol implementation for threshold EdDSA, and we probably are going to opensource it, but I don’t know when.

Note that cggmp21 is a protocol for threshold ECDSA, so it’s not compatible with EdDSA.

**Comment by maurges** [comment]
Technically you can still do ECDSA with CGGMP on ed25519 curve. Please read the comment here: https://docs.rs/cggmp21/latest/cggmp21/supported_curves/index.html - and then you can instantiate this library with any curve from here: https://docs.rs/generic-ec

It's probably not what you want to use though.

**Comment by survived** [comment]
Yeah I assumed the question was about EdDSA, not ECDSA over ed25519 curve

**Comment by survived** [comment]
Btw I forgot to mention here that threshold EdDSA is opensourced: https://github.com/LFDT-Lockness/givre
