### ISSUE TITLE
`key_share` crate and module conflict under `rustc 1.80.1`

### ISSUE THREAD

**Issue by manel1874** [dfns/cggmp21#110]
Hello team, 

I ran `cargo build` under the `cggmp21` crate and I am getting an `ambiguous name` error:

```bash
   Compiling key-share v0.4.2 (/home/manuelsantos/GitHub/cggmp21/key-share)
   Compiling paillier-zk v0.4.1
   Compiling cggmp21-keygen v0.3.1 (/home/manuelsantos/GitHub/cggmp21/cggmp21-keygen)
   Compiling cggmp21 v0.4.1 (/home/manuelsantos/GitHub/cggmp21/cggmp21)
error[E0659]: `key_share` is ambiguous
   --> cggmp21/src/lib.rs:306:5
    |
306 | use key_share::AnyKeyShare;
    |     ^^^^^^^^^ ambiguous name
    |
    = note: ambiguous because of multiple potential import sources
    = note: `key_share` could refer to a crate passed with `--extern`
    = help: use `::key_share` to refer to this crate unambiguously
note: `key_share` could also refer to the module defined here
   --> cggmp21/src/lib.rs:313:1
    |
313 | pub mod key_share;
    | ^^^^^^^^^^^^^^^^^^
    = help: use `crate::key_share` to refer to this module unambiguously

For more information about this error, try `rustc --explain E0659`.
error: could not compile `cggmp21` (lib) due to previous error
```

It compiles the `key-share v0.4.2` crate first, so it enters in conflict with the `key_share` module from above.

**Comment by manel1874** [comment]
This works under a rust nightly version actually. Suggestion: maybe it is useful to have that written in the README file.

**Comment by maurges** [comment]
This works in non-nightly too, it runs fine for me with `rustc 1.80.0`, and has been for multiple versions now. What rustc does it fail for you with?

**Comment by manel1874** [comment]
Thanks for your answer,

Nightly: `rustc 1.83.0-nightly (bd53aa3bf 2024-09-02)`
Stable: `rustc 1.80.1 (3f5fd8dd4 2024-08-06)`

Just tested with `rustc 1.80.0` and it works as well! It is failing for `rustc 1.80.1` for some reason.

**Comment by maurges** [comment]
Still can't reproduce, builds fine for me with latest rustc in rustup which is `rustc 1.80.1 (3f5fd8dd4 2024-08-06)`

**Comment by maurges** [comment]
It's weird if it only appears on 1.80.1, and not on any older or later versions. Looks like a compiler bug, or something wrong with your test setup.

**Comment by maurges** [comment]
Tried `rustc 1.81.0 (eeb90cda1 2024-09-04)`, still can't reproduce. Can you verify that it still happens to you? Can you give the OS and libc details?

**Comment by manel1874** [comment]
Thank you for taking the time to look into it.

 I ran `cargo clean` and `cargo test` with 1.80.1 and everything is building fine. It's weird, I cannot reproduce the error anymore. I guess we can close this issue. Thanks!
