### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by manel1874** [dfns/cggmp21#112]
Just noting here that there are some dead links due to your repo change:

1. "A self-contained description of the protocols we implemented is available [here](https://dfns.github.io/cggmp21/cggmp21-spec.pdf)" -> "A self-contained description of the protocols we implemented is available [here](https://lfdt-lockness.github.io/cggmp21/cggmp21-spec.pdf)"
2. "Our implementation has been audited by Kudelski. Report can be found [here](https://github.com/dfns/cggmp21/blob/m/docs/audit_report.pdf)." -> "Our implementation has been audited by Kudelski. Report can be found [here](https://github.com/lfdt-lockness/cggmp21/blob/m/docs/audit_report.pdf)."
3. "There are other (small) differences in the implementation compared to the original paper (mostly typo fixes); they are all documented in [the spec](https://dfns.github.io/cggmp21/cggmp21-spec.pdf)" -> "There are other (small) differences in the implementation compared to the original paper (mostly typo fixes); they are all documented in [the spec](https://lfdt-lockness.github.io/cggmp21/cggmp21-spec.pdf)"

**Comment by survived** [comment]
Thanks for noticing! I will update them
